import React from 'react'

const Experience = () => {
  return (
    <div>

      <h1>MY EXPERIENCE</h1>
      <p>
        -PROGRAMATE EDUCAMAS-6 MESES.
        RELIZACION DEL BOOKCAM COMPLETO RELIZANDO PROYECTOS CON: HTML , CSS,
        JAVASCRIPT, REACT ADEMAS DEL USO DE HERRAMIENTAS COMO: FIGMA, PADLET,
        TRELLO
        <br/>
        -VITAL PLANET SPA- 6MESES.
        MANEJO DE REDESS POR MEDIO DE INSTAGRAM Y WHATSAPP
        EDICION DE VIDEOS Y FOTOS PARA PUBLICIDAD
        ATENCION DE USUARIOS VIRTUAL Y PRESENCIAL
          <br/>
        -SANTA ROSALIA UEM (CLINICA)
        ATENCION AL USUARIO PRESENCIALMENTE QUEJAS Y RECLAMOS
        FACTURACIONES, REALIZACION DE PRESUPUESTOS
      </p>
    </div>
  )
}

export default Experience