import React from 'react'

const Studies = () => {
  return (
    <div>
      <h1>MY STUDIES</h1>

      
       <p> - PROGRAMATE  EDUCAMAS-DESARROLLADOR FULL STARK .

        DESARROLLANDOME POR 6 MESES EN ACTIVIDADES PRACTICAS SIENDO  EL DESARROLLO DE PROYECTOS
        EL METODO DE ESTUDIO


        -PLATZI.

        CURSOS BASICO DE HTML Y CSS
        CURSO BASICO DE JAVASCRIPT
        CURSO DE INGLES NIVEL INTERMEDIO-EN CURSO ACTUALMENTE


        -INCES, INSTUTUTO NACIONAL DE CAPACITACIONES-2 AÑO.

        ESTUDIOS TECNICOS EN ADMINISTRACION DE EMPRESAS
        Y PASANTIAS EN EMPRESA SANTA ROSALIA-1 AÑO
        </p>
    </div>
  )
}

export default Studies